name: Build and Release

on:
  workflow_dispatch:
  push:
    branches:
      - main

concurrency:
  group: ${{ github.ref }}
  cancel-in-progress: true

jobs:

  build:
    
    runs-on: ubuntu-latest

    strategy:
      matrix:
        goos: [ 'linux', 'windows', 'darwin' ]
        goarch: [ 'amd64', 'arm64' ]

    steps:

      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: 1.23

      - name: Build
        run: |
          mkdir -p dist
          GOOS=${{ matrix.goos }} GOARCH=${{ matrix.goarch }} go build -o dist/worktrack-${{ matrix.goos }}-${{ matrix.goarch }}

      - name: Upload binary as artifact
        uses: actions/upload-artifact@v4
        with:
          name: worktrack-${{ matrix.goos }}-${{ matrix.goarch }}
          path: dist/worktrack-${{ matrix.goos }}-${{ matrix.goarch }}
          retention-days: 7

